sudo: false

language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

env:
  - TASK=build

# dependent apt packages
addons:
  apt:
    packages:
      - libeigen3-dev

before_install: true

install: true

script:
  - make -C src

notifications:
# Emails are sent to the committer's git-configured email address by default,
  email:
    on_success: change
    on_failure: always
  #slack: dmlc:NmroCzntCiWOuxUZpii40USd
