sudo: false

language: cpp

os:
  - linux

compiler:
  - gcc

env:
  - TASK=build

# dependent apt packages
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libeigen3-dev

before_install: true

install:
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi

script:
  - make -C src

notifications:
# Emails are sent to the committer's git-configured email address by default,
  email:
    on_success: change
    on_failure: always
